version: "3.9"
#######################################################################################
# NB: this docker-compose file was wrote to be run/up with already built images for : #
# - web service = web_img                                                             #
# - nginx service = nginx_img                                                         #
# => Actually these 2 images are built during GitHub Actions CI/CD workflow           #
# (see .github/workflows/CI_CD_workflow.yml)                                          #
#######################################################################################

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  web:
    image: web_img_prod
    build:
      context: ./pur_beurre_app
      dockerfile: Dockerfile.prod
    command: gunicorn project_config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    image: nginx_img_prod
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:

