version: "3"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  web:
    image: web_img
    build:
      context: ./pur_beurre_app
      dockerfile: Dockerfile.prod
    command: newrelic-admin run-program gunicorn project_config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:
      NEW_RELIC_APP_NAME: P11_purbeurre_scaleway
    depends_on:
      - db
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/local_prod:/etc/nginx/conf.d
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:

