version: "3.9"
#######################################################################################
# NB: this docker-compose file was wrote to be run/up with already built images for : #
# - web service = web_img                                                             #
# - nginx service = nginx_img                                                         #
# => Actually these 2 images are built during GitHub Actions CI/CD workflow           #
# (see .github/workflows/CI_CD_workflow.yml)                                          #
#######################################################################################

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  web:
    image: web_img
    build:
      context: ./pur_beurre_app
      dockerfile: Dockerfile.prod
    command: newrelic-admin run-program gunicorn project_config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:
      NEW_RELIC_APP_NAME: P11_purbeurre_scaleway
    depends_on:
      - db
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/home/app/web/staticfiles
      - /var/www/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:

