version: "3"
#######################################################################################
# NB: this docker-compose file was wrote to be run/up with already built image for :  #
# - service "web" --> image = "web_img"                                               #
#                                                                                     #
# => because it's mainly used via GitHub Actions CI/CD workflow. The web_img image is
# builts during the .github/workflows/CI_CD_workflow.yml execution..                  #
#                                                                                     #
# NB: Use ./docker-compose.local.prod.yml that builds the image..                     #
#######################################################################################

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
  web:
    image: web_img
    command: newrelic-admin run-program gunicorn project_config.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    environment:
      NEW_RELIC_APP_NAME: P11_purbeurre_scaleway
    depends_on:
      - db
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/home/app/web/staticfiles
      - /var/www/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:

