version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=p10_pg_db_dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    image: web_img_dev
    build:
      context: ./pur_beurre_app
      dockerfile: Dockerfile
    command: newrelic-admin run-program gunicorn project_config.wsgi:application --bind 0.0.0.0:8000
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    environment:
      NEW_RELIC_APP_NAME: P10_pur_beurre_app_dev
    depends_on:
      - db

volumes:
  postgres_data:
